name: fsg
description: "FlutterSceneKit - lightweight library for adding OpenGL ES 3D rendering to flutter applications"
version: 0.0.1
homepage: https://pub.dev

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_angle: ^0.3.9
  mutex: ^3.1.0
  vector_math: ^2.2.0
  visibility_detector: ^0.4.0+2
  web: ^1.1.1
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9 # Add the correct test package
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
